server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**

        - id: services-service
          uri: http://localhost:8082
          predicates:
            - Path=/services/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
